### ISSUE TITLE
[BUG] Server doesn't start after reboot

### ISSUE THREAD

**Issue by mdcrivello** [huggingface/llm-ls#37]
I'm using an intel based mac (ventura 13.4) using vscode (1.83.1) with the llm-vscode extension (v0.1.6) which I believe is using llm-ls 0.4.0.

If I shutdown my mac with vscode running and the extension enabled, the next time I start vscode, the llm-ls server fails to start with the following error: `2023-10-23 17:15:31.351 [info] thread 'main' panicked at crates/llm-ls/src/main.rs:796:18:`. 

Seems like the error is related to the time check so I added the Instant::now() value to the output error message, recompiled the binary, and pointed llm-vscode extension to it. I got the following error: `2023-10-23 17:16:40.711 [info] thread 'main' panicked at 'Expected instant to be in bounds. Value of Instant.now is: Instant { t: 190814174805 }, tried to subtract a duration of 3600s', crates/llm-ls/src/main.rs:796:36`

The time is way off for some reason causing the check to fail. I then deleted lines 795 and 796, recompiled, and now llm-vscode works across reboots. This is not a proper solution to this problem and I'm not a Rust developer but I wanted to bring the issue to your attention.

**Comment by mikeshi80** [comment]
I think this issue is related to #45
